[2025-10-15T20:58:12.950+0000] {processor.py:157} INFO - Started process (PID=6225) to work on /opt/airflow/dags/test.py
[2025-10-15T20:58:12.954+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-10-15T20:58:12.961+0000] {logging_mixin.py:151} INFO - [2025-10-15T20:58:12.960+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-10-15T20:58:13.094+0000] {logging_mixin.py:151} INFO - [2025-10-15T20:58:13.073+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 6, in <module>
    from py_files.get import ChromebrowserOption, OpenChromeBrowser, StockResults
  File "/opt/airflow/dags/py_files/get.py", line 3, in <module>
    import webdriver
ModuleNotFoundError: No module named 'webdriver'
[2025-10-15T20:58:13.102+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-10-15T20:58:13.169+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test.py took 0.229 seconds
[2025-10-15T20:58:43.551+0000] {processor.py:157} INFO - Started process (PID=6283) to work on /opt/airflow/dags/test.py
[2025-10-15T20:58:43.555+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-10-15T20:58:43.562+0000] {logging_mixin.py:151} INFO - [2025-10-15T20:58:43.562+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-10-15T20:58:43.678+0000] {logging_mixin.py:151} INFO - [2025-10-15T20:58:43.652+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 6, in <module>
    from py_files.get import ChromebrowserOption, OpenChromeBrowser, StockResults
  File "/opt/airflow/dags/py_files/get.py", line 3, in <module>
    import webdriver
ModuleNotFoundError: No module named 'webdriver'
[2025-10-15T20:58:43.685+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-10-15T20:58:43.745+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test.py took 0.206 seconds
[2025-10-15T20:59:14.276+0000] {processor.py:157} INFO - Started process (PID=6341) to work on /opt/airflow/dags/test.py
[2025-10-15T20:59:14.280+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-10-15T20:59:14.290+0000] {logging_mixin.py:151} INFO - [2025-10-15T20:59:14.289+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-10-15T20:59:14.405+0000] {logging_mixin.py:151} INFO - [2025-10-15T20:59:14.376+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 6, in <module>
    from py_files.get import ChromebrowserOption, OpenChromeBrowser, StockResults
  File "/opt/airflow/dags/py_files/get.py", line 3, in <module>
    import webdriver
ModuleNotFoundError: No module named 'webdriver'
[2025-10-15T20:59:14.412+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-10-15T20:59:14.476+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test.py took 0.214 seconds
[2025-10-15T20:59:45.018+0000] {processor.py:157} INFO - Started process (PID=6400) to work on /opt/airflow/dags/test.py
[2025-10-15T20:59:45.022+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-10-15T20:59:45.031+0000] {logging_mixin.py:151} INFO - [2025-10-15T20:59:45.030+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-10-15T20:59:45.345+0000] {logging_mixin.py:151} INFO - [2025-10-15T20:59:45.324+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 6, in <module>
    from py_files.get import ChromebrowserOption, OpenChromeBrowser, StockResults
  File "/opt/airflow/dags/py_files/get.py", line 3, in <module>
    import webdriver
ModuleNotFoundError: No module named 'webdriver'
[2025-10-15T20:59:45.352+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-10-15T20:59:45.407+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test.py took 0.403 seconds
[2025-10-15T21:00:15.787+0000] {processor.py:157} INFO - Started process (PID=6458) to work on /opt/airflow/dags/test.py
[2025-10-15T21:00:15.791+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-10-15T21:00:15.800+0000] {logging_mixin.py:151} INFO - [2025-10-15T21:00:15.798+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-10-15T21:00:15.903+0000] {logging_mixin.py:151} INFO - [2025-10-15T21:00:15.887+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 6, in <module>
    from py_files.get import ChromebrowserOption, OpenChromeBrowser, StockResults
  File "/opt/airflow/dags/py_files/get.py", line 3, in <module>
    import webdriver
ModuleNotFoundError: No module named 'webdriver'
[2025-10-15T21:00:15.909+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-10-15T21:00:15.958+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test.py took 0.184 seconds
[2025-10-15T21:00:46.718+0000] {processor.py:157} INFO - Started process (PID=6516) to work on /opt/airflow/dags/test.py
[2025-10-15T21:00:46.721+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-10-15T21:00:46.727+0000] {logging_mixin.py:151} INFO - [2025-10-15T21:00:46.726+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-10-15T21:00:46.837+0000] {logging_mixin.py:151} INFO - [2025-10-15T21:00:46.806+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 6, in <module>
    from py_files.get import ChromebrowserOption, OpenChromeBrowser, StockResults
  File "/opt/airflow/dags/py_files/get.py", line 3, in <module>
    import webdriver
ModuleNotFoundError: No module named 'webdriver'
[2025-10-15T21:00:46.843+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-10-15T21:00:46.885+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test.py took 0.181 seconds
[2025-10-15T21:01:17.404+0000] {processor.py:157} INFO - Started process (PID=6574) to work on /opt/airflow/dags/test.py
[2025-10-15T21:01:17.413+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-10-15T21:01:17.431+0000] {logging_mixin.py:151} INFO - [2025-10-15T21:01:17.429+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-10-15T21:01:17.672+0000] {logging_mixin.py:151} INFO - [2025-10-15T21:01:17.620+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 6, in <module>
    from py_files.get import ChromebrowserOption, OpenChromeBrowser, StockResults
  File "/opt/airflow/dags/py_files/get.py", line 3, in <module>
    import webdriver
ModuleNotFoundError: No module named 'webdriver'
[2025-10-15T21:01:17.686+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-10-15T21:01:17.838+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test.py took 0.464 seconds
[2025-10-15T21:01:28.228+0000] {processor.py:157} INFO - Started process (PID=6589) to work on /opt/airflow/dags/test.py
[2025-10-15T21:01:28.231+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-10-15T21:01:28.239+0000] {logging_mixin.py:151} INFO - [2025-10-15T21:01:28.238+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-10-15T21:01:29.714+0000] {logging_mixin.py:151} INFO - [2025-10-15T21:01:29.685+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 8, in <module>
    from airflow.operators.selenium_plugin import SeleniumOperator
ModuleNotFoundError: No module named 'airflow.operators.selenium_plugin'
[2025-10-15T21:01:29.726+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-10-15T21:01:29.804+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test.py took 1.585 seconds
[2025-10-15T21:02:00.102+0000] {processor.py:157} INFO - Started process (PID=6648) to work on /opt/airflow/dags/test.py
[2025-10-15T21:02:00.105+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-10-15T21:02:00.114+0000] {logging_mixin.py:151} INFO - [2025-10-15T21:02:00.113+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-10-15T21:02:00.987+0000] {logging_mixin.py:151} INFO - [2025-10-15T21:02:00.975+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 8, in <module>
    from airflow.operators.selenium_plugin import SeleniumOperator
ModuleNotFoundError: No module named 'airflow.operators.selenium_plugin'
[2025-10-15T21:02:00.991+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-10-15T21:02:01.047+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test.py took 0.959 seconds
[2025-10-15T21:02:32.145+0000] {processor.py:157} INFO - Started process (PID=6707) to work on /opt/airflow/dags/test.py
[2025-10-15T21:02:32.151+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-10-15T21:02:32.177+0000] {logging_mixin.py:151} INFO - [2025-10-15T21:02:32.175+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-10-15T21:02:33.342+0000] {logging_mixin.py:151} INFO - [2025-10-15T21:02:33.323+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 8, in <module>
    from airflow.operators.selenium_plugin import SeleniumOperator
ModuleNotFoundError: No module named 'airflow.operators.selenium_plugin'
[2025-10-15T21:02:33.347+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-10-15T21:02:33.405+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test.py took 1.290 seconds
[2025-10-15T21:02:34.903+0000] {processor.py:157} INFO - Started process (PID=6722) to work on /opt/airflow/dags/test.py
[2025-10-15T21:02:34.906+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-10-15T21:02:34.913+0000] {logging_mixin.py:151} INFO - [2025-10-15T21:02:34.912+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-10-15T21:02:36.205+0000] {logging_mixin.py:151} INFO - [2025-10-15T21:02:36.171+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 26, in <module>
    get_webdriver_options_b = PythonOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 177, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 812, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/task_group.py", line 230, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'get_webdriver_options_b' has already been added to the DAG
[2025-10-15T21:02:36.207+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-10-15T21:02:36.256+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test.py took 1.364 seconds
[2025-10-15T21:03:07.185+0000] {processor.py:157} INFO - Started process (PID=6781) to work on /opt/airflow/dags/test.py
[2025-10-15T21:03:07.192+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-10-15T21:03:07.210+0000] {logging_mixin.py:151} INFO - [2025-10-15T21:03:07.208+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-10-15T21:03:08.732+0000] {logging_mixin.py:151} INFO - [2025-10-15T21:03:08.718+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 26, in <module>
    get_webdriver_options_b = PythonOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 177, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 812, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/task_group.py", line 230, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'get_webdriver_options_b' has already been added to the DAG
[2025-10-15T21:03:08.734+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2025-10-15T21:03:08.783+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test.py took 1.619 seconds
[2025-10-15T21:03:35.757+0000] {processor.py:157} INFO - Started process (PID=6837) to work on /opt/airflow/dags/test.py
[2025-10-15T21:03:35.760+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-10-15T21:03:35.772+0000] {logging_mixin.py:151} INFO - [2025-10-15T21:03:35.771+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-10-15T21:03:36.859+0000] {processor.py:839} INFO - DAG(s) dict_keys(['scanfile']) retrieved from /opt/airflow/dags/test.py
[2025-10-15T21:03:42.443+0000] {logging_mixin.py:151} INFO - [2025-10-15T21:03:42.442+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-10-15T21:03:42.538+0000] {logging_mixin.py:151} INFO - [2025-10-15T21:03:42.537+0000] {dag.py:3722} INFO - Setting next_dagrun for scanfile to 2025-10-14T00:00:00+00:00, run_after=2025-10-15T00:00:00+00:00
[2025-10-15T21:03:42.667+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test.py took 6.923 seconds
[2025-10-15T21:03:56.524+0000] {processor.py:157} INFO - Started process (PID=6883) to work on /opt/airflow/dags/test.py
[2025-10-15T21:03:56.526+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-10-15T21:03:56.533+0000] {logging_mixin.py:151} INFO - [2025-10-15T21:03:56.532+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-10-15T21:03:57.592+0000] {processor.py:839} INFO - DAG(s) dict_keys(['scanfile']) retrieved from /opt/airflow/dags/test.py
[2025-10-15T21:03:57.626+0000] {logging_mixin.py:151} INFO - [2025-10-15T21:03:57.624+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-10-15T21:03:57.732+0000] {logging_mixin.py:151} INFO - [2025-10-15T21:03:57.731+0000] {dag.py:3722} INFO - Setting next_dagrun for scanfile to 2025-10-14T00:00:00+00:00, run_after=2025-10-15T00:00:00+00:00
[2025-10-15T21:03:57.861+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test.py took 1.344 seconds
[2025-10-15T21:04:28.148+0000] {processor.py:157} INFO - Started process (PID=6943) to work on /opt/airflow/dags/test.py
[2025-10-15T21:04:28.151+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-10-15T21:04:28.157+0000] {logging_mixin.py:151} INFO - [2025-10-15T21:04:28.156+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-10-15T21:04:29.290+0000] {processor.py:839} INFO - DAG(s) dict_keys(['scanfile']) retrieved from /opt/airflow/dags/test.py
[2025-10-15T21:04:29.973+0000] {logging_mixin.py:151} INFO - [2025-10-15T21:04:29.972+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-10-15T21:04:30.020+0000] {logging_mixin.py:151} INFO - [2025-10-15T21:04:30.020+0000] {dag.py:3722} INFO - Setting next_dagrun for scanfile to 2025-10-14T00:00:00+00:00, run_after=2025-10-15T00:00:00+00:00
[2025-10-15T21:04:30.107+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test.py took 1.970 seconds
[2025-10-15T21:05:00.659+0000] {processor.py:157} INFO - Started process (PID=7002) to work on /opt/airflow/dags/test.py
[2025-10-15T21:05:00.666+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-10-15T21:05:00.684+0000] {logging_mixin.py:151} INFO - [2025-10-15T21:05:00.681+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-10-15T21:05:02.004+0000] {processor.py:839} INFO - DAG(s) dict_keys(['scanfile']) retrieved from /opt/airflow/dags/test.py
[2025-10-15T21:05:02.127+0000] {logging_mixin.py:151} INFO - [2025-10-15T21:05:02.125+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-10-15T21:05:02.834+0000] {logging_mixin.py:151} INFO - [2025-10-15T21:05:02.834+0000] {dag.py:3722} INFO - Setting next_dagrun for scanfile to 2025-10-14T00:00:00+00:00, run_after=2025-10-15T00:00:00+00:00
[2025-10-15T21:05:02.893+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test.py took 2.258 seconds
[2025-10-15T21:05:33.082+0000] {processor.py:157} INFO - Started process (PID=7061) to work on /opt/airflow/dags/test.py
[2025-10-15T21:05:33.085+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-10-15T21:05:33.091+0000] {logging_mixin.py:151} INFO - [2025-10-15T21:05:33.091+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-10-15T21:05:34.279+0000] {processor.py:839} INFO - DAG(s) dict_keys(['scanfile']) retrieved from /opt/airflow/dags/test.py
[2025-10-15T21:05:34.631+0000] {logging_mixin.py:151} INFO - [2025-10-15T21:05:34.630+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2025-10-15T21:05:34.711+0000] {logging_mixin.py:151} INFO - [2025-10-15T21:05:34.711+0000] {dag.py:3722} INFO - Setting next_dagrun for scanfile to 2025-10-14T00:00:00+00:00, run_after=2025-10-15T00:00:00+00:00
[2025-10-15T21:05:34.780+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/test.py took 1.714 seconds
